[workspace]
# path of the git-cliff configuration
changelog_config = "cliff.toml"
# update dependencies with `cargo update`
dependencies_update = true
# labels for the release PR
pr_labels = ["release"]
# disable publishing crates to crates.io
publish = false 
# disable GitHub releases - this is handled by cargo-dist
git_release_enable = false
# disable running `cargo-semver-checks`
semver_check = false
